const routes = {
  '/': 'Home',
  '/dashboard': 'Dashboard',
  '/components': 'Components',
  '/charts': 'Charts',
  '/components/buttons': 'Buttons',
  '/components/social-buttons': 'Social Buttons',
  '/components/cards': 'Cards',
  '/components/forms': 'Forms',
  '/components/modals': 'Modals',
  '/components/switches': 'Switches',
  '/components/tables': 'Tables',
  '/components/tabs': 'Tabs',
  '/icons': 'Icons',
  '/icons/font-awesome': 'Font Awesome',
  '/icons/simple-line-icons': 'Simple Line Icons',
  '/widgets': 'Widgets',
  '/profile': 'Profile',
  '/change-password': 'changePassword',
  '/userrole': 'userRole',
  '/userright': 'userRight',
  '/userroletoright': 'userRoleToRight',
  '/create': 'createEmployee',
  '/listapp': 'ListApp',
  '/editapp': 'EditApp',
  '/viewapp/:id': 'ViewApp',
  '/application': 'Profile',
  '/advertiser' : 'Advertiser',
  '/list' : 'listEmployee',
  '/custom-ads' : 'CustomAds',
  '/monetization-network' : 'MonetizationNetwork',
  '/notifications' : 'Notifications',
  '/list-notifications' : 'ListNotifications',
  '/view-notification/:id' : 'ViewNotifications',
  '/view/:id' : 'viewEmployee',
  '/view-document/:id' : 'viewDocument',
  '/document' : 'Document',
  '/document-list' : 'DocumentList'
};
export default routes;
